---
- name: Install required system packages
  apt: name={{ sys_packages }} state=present

# Upload templated haproxy config
- name: Update HAProxy config
  template: 
    src=haproxy.cfg 
    dest=/etc/haproxy/haproxy.cfg
    trim_blocks=false
    backup=no                
  notify: restart haproxy