---
# This playbook deploys the entire web hosting stack
# Database, then file, then control, then web, wpadmin, lb


- name: Configure and deploy the Database
  hosts: database
  become: true
  roles:
    - mariadb