---
- name: Start of Job Monitoring
  hosts: localhost
  tasks:
    - name: Tell Healthchecks.io that we started the playbook
      ansible.builtin.uri:
        url: "{{ SitePlaybookHC }}/start"
        timeout: 10
        force: true

- name: Configure and deploy the Database
  hosts: database
  become: true
  roles:
    - ubuntu
    - mariadb
    - zabbix-agent

- name: Configure and deploy the NFS Server
  hosts: nfs-server
  become: true
  roles:
    - ubuntu  
    - nfs-server
    - zabbix-agent

- name: Configure and deploy the Control Server
  hosts: control
  become: true
  roles:
    - ubuntu
    - nfs-client
    - control
    - zabbix-agent

- name: Configure and deploy the Web Servers
  hosts: web
  become: true
  roles:
    - ubuntu
    - nfs-client
    - nginx
    - zabbix-agent

- name: Configure and deploy the Wordpress Admin Servers
  hosts: wp-admin
  become: true
  roles:
    - ubuntu
    - nfs-client
    - wp-admin
    - zabbix-agent
    - wp-cron

- name: Configure and deploy the Loadbalancer
  hosts: loadbalancers
  become: true
  vars:
    webnodes: "{{ groups['web'] }}"
    wpanodes: "{{ groups['wp-admin'] }}"
  roles:
    - ubuntu  
    - haproxy
    - zabbix-agent

- name: Configure and deploy Tunnel
  hosts: tunnel
  become: true
  roles:
    - ubuntu
    - zabbix-agent

- name: Configure and deploy Bluesky PDS
  hosts: bluesky
  become: true
  roles:
    - ubuntu
    - zabbix-agent

- name: Configure and deploy Health Server
  hosts: zabbix-server
  become: true
  roles:
    - ubuntu

- name: Configure and deploy AzuraCast Radio Server
  hosts: radio
  become: true
  roles:
    - ubuntu
    - zabbix-agent

- name: Configure and deploy Docker Host
  hosts: docker
  become: true
  roles:
    - ubuntu
    - zabbix-agent

- name: End of Job Monitoring
  hosts: localhost
  tasks:
    - name: Tell Healthchecks.io that we finished the playbook
      ansible.builtin.uri:
        url: "{{ SitePlaybookHC }}"
        timeout: 10
        force: true