---
# This playbook deploys the entire web hosting stack
# Database, then file, then control, then web, wpadmin, lb

- name: Configure and deploy the Database
  hosts: database
  become: true
  roles:
    - mariadb
    - ubuntu

- name: Configure and deploy the NFS Server
  hosts: nfs-server
  become: true
  roles:
    - nfs-server
    - ubuntu

#- name: Configure and deploy the Control Server
#  hosts: control
#  become: true
#  roles:
#    - control
#    - ubuntu

#ADD NFS-CLIENT TO CONTROL SERVER, ABOVE CONTROL ROLE. DIRECTORY NEEDS TO EXIST BEFORE WE TRY TO PUT FILES ON IT    