---
# This playbook deploys the entire web hosting stack
# Database, then file, then control, then web, wpadmin, lb

- name: Configure and deploy the Database
  hosts: database
  become: true
  roles:
    - ubuntu
    - mariadb

- name: Configure and deploy the NFS Server
  hosts: nfs-server
  become: true
  roles:
    - ubuntu  
    - nfs-server

- name: Configure and deploy the Control Server
  hosts: control
  become: true
  roles:
    - ubuntu
    - nfs-client
    - control