---
# This playbook deploys the entire web hosting stack
# Database, then file, then control, then web, wpadmin, lb, , Health, Log, Bluesky

- name: Configure and deploy the Database
  hosts: database
  become: true
  roles:
    - ubuntu
    - mariadb

- name: Configure and deploy the NFS Server
  hosts: nfs-server
  become: true
  roles:
    - ubuntu  
    - nfs-server

- name: Configure and deploy the Control Server
  hosts: control
  become: true
  roles:
    - ubuntu
    - nfs-client
    - control

- name: Configure and deploy the Web Servers
  hosts: web
  become: true
  roles:
    - ubuntu
    - nfs-client
    - nginx

- name: Configure and deploy the Wordpress Admin Servers
  hosts: wp-admin
  become: true
  roles:
    - ubuntu
    - nfs-client
    - wp-admin

- name: Configure and deploy the Loadbalancer
  hosts: loadbalancers
  become: true
  vars:
    webnodes: "{{ groups['web'] }}"
    wpanodes: "{{ groups['wp-admin'] }}"
  roles:
    - ubuntu  
    - haproxy

- name: Configure and deploy Tunnel
  hosts: tunnel
  become: true
  roles:
    - ubuntu

- name: Configure and deploy Bluesky PDS
  hosts: bluesky
  become: true
  roles:
    - ubuntu

- name: Configure and deploy Health Server
  hosts: zabbix-server
  become: true
  roles:
    - ubuntu


