---
# Place Nginx Snippets
# We need Jetpack IPs for XML-RPC Control
- name: Setting host facts using complex arguments
  ansible.builtin.set_fact:
    jetpack_ips: "{{ lookup('ansible.builtin.url', 'https://jetpack.com/ips-v4.txt', wantlist=True) }}"

# Placing them here is super weird , but it ensures they are there before any web servers needing them start. 
- name: Add Resource Cache Control snippet if missing
  become: yes
  become_user: root            
  copy: 
    src: cache-control.conf
    dest:  /mnt/Web/Snippets/cache-control.conf
    backup: no
    owner: www-data
    group: www-data
    mode: 0644

- name: Add our FastCGI Cache snippet if missing
  become: yes
  become_user: root            
  copy: 
    src: fastcgicache.conf
    dest:  /mnt/Web/Snippets/fastcgicache.conf
    backup: no
    owner: www-data
    group: www-data
    mode: 0644

- name: Add PHP snippet if missing
  become: yes
  become_user: root            
  copy: 
    src: php.conf
    dest:  /mnt/Web/Snippets/php.conf
    backup: no
    owner: www-data
    group: www-data
    mode: 0644

- name: Add Wordpress Security snippet if missing
  become: yes
  become_user: root            
  copy: 
    src: wp-block.conf
    dest:  /mnt/Web/Snippets/wp-block.conf
    backup: no
    owner: www-data
    group: www-data
    mode: 0644

- name: Add XML-RPC Block snippet if missing
  become: yes
  become_user: root            
  template: 
    src: xmlrpc.conf
    dest:  /mnt/Web/Snippets/xmlrpc.conf
    backup: no
    owner: www-data
    group: www-data
    mode: 0644