---
- name: Gather package facts
  package_facts:
    manager: "auto"

# Download Agent Deb File
- name: Download Ubuntu 20 Zabbix deb file
  get_url:
    url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0%2Bubuntu20.04_all.deb"
    dest: "/tmp/zabbix.deb"
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

- name: Download Ubuntu 22 Zabbix deb file
  get_url:
    url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0%2Bubuntu22.04_all.deb"
    dest: "/tmp/zabbix.deb"
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")

- name: Download Ubuntu 24 Zabbix deb file
  get_url:
    url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0%2Bubuntu24.04_all.deb"
    dest: "/tmp/zabbix.deb"
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "24")

# Install Deb File
- name: Install Zabbix deb file
  become: true
  apt: deb="/tmp/zabbix.deb"

# Install Agent
- name: install Zabbix Agent 2 
  become: true
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes
  notify: restart zabbix_agent       

- name: Place zabbix-agent config
  become: yes
  template:
    src=zabbix_agent2.conf 
    dest=/etc/zabbix/zabbix_agent2.conf 
    backup=no
  notify: restart zabbix_agent   