# Configure WP Cron
- name: Place WP Cron file
  become: yes
  become_user: root            
  copy: 
    src: /mnt/Web/Ansible/wpcron
    dest: /etc/cron.d/wpcron
    remote_src: yes
    mode: '0644'
    backup: no
