---
- name: Install required system packages
  apt: name={{ sys_packages }} state=present

# Upload SSH Config
- name: Upload custom sqlmode file
  become: yes
  become_user: root
  copy:
    src: 00-servermode.cnf
    dest: /etc/mysql/mariadb.conf.d/00-servermode.cnf
    remote_src: no
  notify: restart mysql       
  
- name: Allow incoming connections
  become: yes
  become_user: root
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address            = 127.0.0.1'
    line: 'bind-address            = 0.0.0.0'
    state: present  
  notify: restart mysql

- name: Ensure .my.cnf exists
  copy:
    src: .my.cnf
    dest: /home/ansible/.my.cnf
    remote_src: no
