---
- name: restart nginx
  become: yes
  service: name=nginx state=restarted enabled=yes
- name: reload nginx
  service: name=nginx state=reloaded enabled=yes
- name: restart php-fpm
  become: yes
  service: name=php8.1-fpm state=restarted enabled=yes