---
- name: Force APT to use IPv4
  copy: 
    src=21000-force-ipv4-transport
    dest=/etc/apt/apt.conf.d/1000-force-ipv4-transport
    backup=no

- name: Upgrade all packages
  apt: upgrade=dist force_apt_get=yes

- name: Set timezone to Eastern
  become: true
  community.general.timezone:
    name: America/New_York