---
- hosts: wp-admin[0]
  become: true
  vars:
    wp_sites: "{{ output.files|map(attribute='path')|map('basename')|list }}"

  tasks: 
    - name: Tell Healthchecks.io that we started the playbook
      ansible.builtin.uri:
        url: "{{ WordpressUpdaterHC }}/start"
        timeout: 10
        force: true

    - name: Generate list of Wordpress sites
      ansible.builtin.find:
        paths: /mnt/Web/Websites/Wordpress
        recurse: no
        file_type: directory
      register: output

    - name: Update Wordpress Plugins
      ansible.builtin.shell:
        cmd: "sudo -u www-data wp plugin update --all"
        chdir: "/mnt/Web/Websites/Wordpress/{{ item }}/public_html/"
      loop: "{{ wp_sites }}"
      throttle: 1
      ignore_errors: True

    - name: Update Wordpress Themes
      ansible.builtin.shell:
        cmd: "sudo -u www-data wp theme update --all"
        chdir: "/mnt/Web/Websites/Wordpress/{{ item }}/public_html/"
      loop: "{{ wp_sites }}"
      throttle: 1
      ignore_errors: True
      
    - name: Update Wordpress Core
      ansible.builtin.shell:
        cmd: "sudo -u www-data wp core update"
        chdir: "/mnt/Web/Websites/Wordpress/{{ item }}/public_html/"
      loop: "{{ wp_sites }}"
      throttle: 1
      ignore_errors: True

    - name: Tell Healthchecks.io that we finished the playbook
      ansible.builtin.uri:
        url: "{{ WordpressUpdaterHC }}"
        timeout: 10
        force: true