---
- name: Install required system packages
  apt: name={{ sys_packages }} state=present  

- name: Check if web directory has files
  stat: 
    path: /mnt/Web/data.txt
  register: nfs_share_data

- name: Create Web directory
  ansible.builtin.file:
    path: /mnt/Web
    state: directory
    mode: '0755'
  when: nfs_share_data.stat.exists == false

# Add NFS Export for Nginx content
- name: Add NFS export for nginx content
  become: yes
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: /mnt/Web/		10.90.90.0/24(rw,async,no_root_squash,no_subtree_check)
    create: yes
  notify: restart nfs    